# Generated by Django 4.2.7 on 2024-03-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerceProDuct', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Product',
        ),
    ]
